name: Build for multiple SDK versions

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: ["", "6.0.x", "7.0.x"]
        # these entries will mesh with the above combinations
        include:
          # just use what's in the repo
          - global-json-file: "global.json"
            dotnet-version: ""
            include-prerelease: false
            label: "repo global.json"
            continue-on-error: false
            build_net7: false
          # latest 6.0 stable
          - global-json-file: "global.json"
            dotnet-version: "6.0.x"
            include-prerelease: false
            label: "6.0 stable"
            continue-on-error: false
            build_net7: false
          # latest 7.0 preview
          - global-json-file: "global.json"
            dotnet-version: "7.0.x"
            include-prerelease: true
            label: "7.0 preview"
            continue-on-error: true
            build_net7: true
      fail-fast: false # we have timing issues on some OS, so we want them all to run
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    name: Build on ${{matrix.os}} for ${{ matrix.label }}

    # we don't want the 7-preview builds to break the PR merge, so those should be optional
    continue-on-error: ${{ matrix.continue-on-error }}
    steps:
      - uses: actions/checkout@v3

      # setup .NET per the repo global.json
      - name: Setup .NET
        uses: actions/setup-dotnet@v2

      # let's make sure we're on the version we think we are.
      - name: Announce .NET version
        run: dotnet --info

      - name: Restore tools
        run: dotnet tool restore

      - name: Run build and test
        run: dotnet run --project build -- -t Pack
        env:
          TestPreview: ${{ matrix.build_net7 }}

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: out/
